CREATE TABLE
  public.ore_type (
    id serial NOT NULL,
    name character varying(255) NOT NULL,
    emoji character varying(255) NOT NULL
  );

ALTER TABLE
  public.ore_type
ADD
  CONSTRAINT "Ore_Type_pkey" PRIMARY KEY (id);

CREATE TABLE
  public.ore_point (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    ore_type integer NOT NULL,
    x integer NOT NULL,
    y integer NOT NULL
  );

ALTER TABLE
  public.ore_point
ADD
  CONSTRAINT "Ore_Point_pkey" PRIMARY KEY (id);

CREATE TABLE
  public.occupy_table (
    ore_point_id integer NOT NULL,
    guild_id bigint NOT NULL,
    user_id bigint NOT NULL,
    due_time timestamp with time zone NOT NULL,
    battle_user_id bigint NULL
  );

ALTER TABLE
  public.occupy_table
ADD
  CONSTRAINT "Occupy_Table_pkey" PRIMARY KEY (guild_id);

insert into "public"."ore_type" ("emoji", "id", "name") values (':copper_ore:1222550112388251668', 1, '金屬礦石'), (':coal:1222552834902327407', 2, '石炭'), (':sulfur:1222553853061234688', 4, '硫磺'), (':quartz:1222560703550853231', 8, '純水晶');
insert into "public"."ore_point" ("id", "name", "ore_type", "x", "y") values (1, '破敗教會', 1, 71, -404), (2, '要塞遺跡', 1, 155, -393), (3, '丘陵海角', 1, 7, -529), (4, '修行者瀑布', 1, -249, -456), (5, '竹林深處', 1, -343, -253), (6, '探究者歧路', 1, -255, -212), (7, '彩蝶之森', 1, -77, -317), (8, '偽善者之丘', 1, 91, -263), (9, '湖畔山丘', 1, -32, -170), (10, '花兔山山頂', 1, 0, -82), (11, '濕地之島旁', 3, 268, -227), (12, '草熊貓之森', 1, 252, -93), (13, '守護者密域', 3, 187, -40), (14, '神速密域', 1, 310, -38), (15, '古代文明遺跡', 1, -418, -606), (16, '黑曜火山山腰', 1, -536, -479), (17, '黑曜火山山頂', 1, -636, -496), (18, '火山黑市商人', 1, -766, -672), (19, '魔淵龍北側山頂', 1, -580, -352), (20, '黑曜火山北側', 1, -674, -291), (21, '鯊小子的地盤', 2, 149, -208), (22, '草熊貓之森西側', 2, 200, -114), (23, '守護者密域山坡', 2, 155, -67), (24, '神速密域南側', 2, 290, -21), (25, '通往雪山的岔路', 2, 101, 26), (26, '霜凍雪山山腳', 2, 101, 59), (27, '日暮沙地東側', 2, -96, -119), (28, '日暮沙地西側', 2, -157, -89), (29, '日暮沙地北側', 2, -125, -83), (30, '黒曜火山東南', 2, -465, -676), (31, '邊遠漁村', 2, -511, -722), (32, '火山阿努比斯', 2, -572, -648), (33, '黒曜火山瀑布', 2, -604, -724), (34, '黒曜火山湖島', 2, -705, -640), (35, '黒曜火山南側', 2, -695, -733), (36, '黒曜火山西南', 2, -735, -695), (37, '冥鎧蠍入口', 2, 515, 66), (38, '冥鎧蠍高地', 2, 591, 151), (39, '冥鎧蠍高地東側', 2, 645, 154), (40, '自衛隊高塔東側', 2, 622, 311), (41, '沙丘入口高地南側', 2, 266, 212), (42, '沙丘入口高地', 2, 290, 242), (43, '沙漠之鎮東北', 2, 436, 432), (44, '雷冠龍東側', 2, 435, 521), (45, '雷冠龍北側', 2, 334, 560), (46, '雷冠龍南側', 2, 320, 500), (47, '永炎同心會高塔', 4, -596, -518), (48, '魔淵龍岩漿湖', 4, -593, -403), (49, '黒曜火山山腳', 4, -743, -444), (50, '空渦龍', 4, -739, -339), (51, '霜凍雪山', 8, 206, 96), (52, '不溶湖東側', 8, -209, 249), (53, '白銀靈峰山腰', 8, -253, 394), (54, '喚冬獸西側', 8, -417, 473), (55, '喚冬獸東側', 8, -308, 542), (56, '白銀靈峰北側', 8, -139, 581);